import '../globals.css'
import { Inter } from 'next/font/google'
// import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Dashboard',
//   description: 'Generated by create next app',
// }

export default function layout({ children }) {
  return (
    <div>
      <p>------</p>
      <p>ini adalah dashboard</p>
      {children}
    </div>
  )
}
